[package]
name = "siplane-nspawn-runner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eventsource-client = "0.11.0"
futures = "0.3.29"
tokio = { version = "1.34.0", features = ["rt", "macros", "rt-multi-thread"] }
