coordinator_base_url = "http://localhost:4000"
host_veth_name = "siplanect0"
board_id = "ed8d3c39-6d34-41af-9fba-ff34109d9dbe"
keepalive_timeout = 60
reconnect_wait = 10

[environments.c4e08e00-cfb0-46d1-83eb-ee62e128cc70]
init = "/nix/store/y3h62baa8lpcxjh48pbf4y870944jxqf-nixos-system-si-pton-arty35-0-23.05.git.1a3c95e3b23b/init"
shutdown_timeout = 30
control_socket_path = "/siplane-ctrl"

[[environments.c4e08e00-cfb0-46d1-83eb-ee62e128cc70.mount]]
src = "/nix/store"
dst = "/nix/store"
readonly = true

[[environments.c4e08e00-cfb0-46d1-83eb-ee62e128cc70.mount]]
src = "/nix/var/nix/db"
dst = "/nix/var/nix/db"
readonly = true

[[environments.c4e08e00-cfb0-46d1-83eb-ee62e128cc70.mount]]
src = "/nix/var/nix/daemon-socket"
dst = "/nix/var/nix/daemon-socket"
readonly = true

[environments.c4e08e00-cfb0-46d1-83eb-ee62e128cc70.zfsroot]
parent = "rpool/siplane-nspawn"
mount_base = "/var/lib/siplane/root"
quota = "10G"