coordinator_base_url = "http://localhost:4000"
board_id = "ed8d3c39-6d34-41af-9fba-ff34109d9dbe"

[environments.c4e08e00-cfb0-46d1-83eb-ee62e128cc70]
id = "nixos_dev"
version = "v1.0"
init = "/nix/store/iq67l0chww1m154smd0v1psfqrg55wz4-nixos-system-si-pton-arty35-0-23.05.git.9075cba53e86/init"