coordinator_base_url = "http://localhost:4000"
board_id = "ed8d3c39-6d34-41af-9fba-ff34109d9dbe"
keepalive_timeout = 60
reconnect_wait = 10

[environments.c4e08e00-cfb0-46d1-83eb-ee62e128cc70]
init = "/nix/store/l13zllb1vpxy8q7r4hlpwxxn1rl0kzs2-nixos-system-si-pton-arty35-0-23.11.git.b4372c4924d9/init"
shutdown_timeout = 30

[[environments.c4e08e00-cfb0-46d1-83eb-ee62e128cc70.mount]]
src = "/nix/store"
dst = "/nix/store"
readonly = true

[[environments.c4e08e00-cfb0-46d1-83eb-ee62e128cc70.mount]]
src = "/nix/var/nix/db"
dst = "/nix/var/nix/db"
readonly = true

[[environments.c4e08e00-cfb0-46d1-83eb-ee62e128cc70.mount]]
src = "/nix/var/nix/daemon-socket"
dst = "/nix/var/nix/daemon-socket"
readonly = true

[environments.c4e08e00-cfb0-46d1-83eb-ee62e128cc70.zfsroot]
parent = "rpool/siplane-nspawn"
mount_base = "/var/lib/siplane/root"
quota = "10G"