coordinator_base_url = "http://localhost:4000"
board_id = "8bfde627-583b-4935-a3e7-f259868eaec2"

[environments.nixos_dev_2305_v1_0]
id = "nixos_dev"
version = "v1.0"
init = "/nix/store/y3h62baa8lpcxjh48pbf4y870944jxqf-nixos-system-si-pton-arty35-0-23.05.git.1a3c95e3b23b/init"