[workspace]
resolver = "2"
members = [
    "treadmill-rs",
    "nspawn-runner",
    "puppet",
    "sse-connector",
    "unix-seqpacket-control-socket",
    "rendezvous-server",
    "rendezvous-proxy",
]
